version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taskmanager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: chaveSuperSecretaParaJWT2026

  task-service:
    build: ./backend/task-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taskmanager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - task-service

volumes:
  postgres_data:
